export default [
    {
        id:"P001",
        name:"Nimal",
        nationality:"Colombo",
        gender:"male",
        status:false
    },{
        id:"P002",
        name:"kamal",
        nationality:"Colombo",
        gender:"male",
        status:true
    },{
        id:"P003",
        name:"Sunimal",
        nationality:"Colombo",
        gender:"female",
        status:true
    },{
        id:"P004",
        name:"pawan",
        nationality:"Colombo",
        gender:"male",
        status:false
    },{
        id:"P005",
        name:"Nimal",
        nationality:"Colombo",
        gender:"female",
        status:true
    },{
        id:"P006",
        name:"sunil",
        nationality:"Colombo",
        gender:"male",
        status:false
    },{
        id:"P006",
        name:"sonal",
        nationality:"Colombo",
        gender:"male",
        status:true
    },{
        id:"P007",
        name:"kalum",
        nationality:"Colombo",
        gender:"female",
        status:false
    }
]